GET http://localhost:5075/tasks
###
GET http://localhost:5075/tasks/5
###
POST http://localhost:5075/tasks
Content-Type: application/json

{
  "name" : "Minecraft",
  "categoryId" : 2,
  "priority": 20,
  "dueDate": "2011-11-18"
}

###
PUT http://localhost:5075/tasks/5
Content-Type: application/json

{
  "name" : "2",
  "categoryId" : 1,
  "priority": 20,
  "dueDate": "2011-11-18"
}

###
DELETE http://localhost:5075/tasks/2